### PR TITLE
fix: add cause to transaction errors on transaction commit

### PR DESCRIPTION
**Pull request by rockwotj**
Right now if a transaction fails due to a precondition failure (which are retried, which is another bug) for example trying to update a document that doesn't exist you get a bad error message of "too many retries". Ideally retry is smarter, but this is a easy change that propagates the underlying error up to the ApiFuture result.

/cc @schmidt-sebastian @BenWhitehead

### CODE REVIEW

**Comment by BenWhitehead** [comment]
@rockwotj Can you run `mvn com.coveo:fmt-maven-plugin:format` to get the code format pre-submit to pass?

**Comment by schmidt-sebastian** [comment]
FYI: We will shortly be addressing the transaction retry behavior across all of our SDKs.

**Comment by schmidt-sebastian** [comment]
@rockwotj Can you update the PR title to follow conventionalcommits.org?

It this case it would be: "fix: ddd cause to transaction errors on transaction commit"

**Comment by BenWhitehead** [comment]
Thanks for the improvement @rockwotj!

**Pull request merged**
