### PR TITLE
docs: remove dual-homed region tags

### PR DESCRIPTION
**Pull request by Strykrol**
Removes unnecessary region tags now that new ones have proliferated in docs. Added wrapped region tags to align with other same-language Firestore samples.

### CODE REVIEW

**Comment by Strykrol** [comment]
Region tag violations are resolved in (submitted) cl/376017137, which hasn't quite percolated apparently.

**Review by crwilcox — APPROVED** [review]

**Comment by Strykrol** [comment]
Could I please get someone to refresh the snippet bot? I am expecting these violations to resolve.

**Comment by Strykrol** [comment]
Not sure why the units would have failed, but I need the updated status reports so I can see what to fix (if problems are still present).

**Comment by Strykrol** [comment]
Could someone please rerun or otherwise expedite the tests?

**Comment by tmatsuo** [comment]
@Strykrol I added `kokoro:force-run` and pushed the approve button for Github workflow.

**Comment by Strykrol** [comment]
Two things:

- I cannot merge this myself, someone else will need to please :)
- I'm wrapping up my contract @ Google, but can continue updating this PR if needed

**Review by suztomo — DISMISSED** [review]

**Comment by meredithslota** [comment]
Closing in favor of https://github.com/googleapis/java-firestore/pull/1122

**Pull request closed without merging**
