### PR TITLE
fix: revert "Feat: Record serialization/deserialization"

### PR DESCRIPTION
**Pull request by milaGGL**
This PR is resulting to java cloud bom failure. Reverting the change back till we fixed the java version conflict.

### CODE REVIEW

**Review by ldetmer — APPROVED** [review]

**Review by suztomo — APPROVED** [review]

**Comment by suztomo** [comment]
When merging this pull request ensure you have "fix:" in the prefix in the commit message. This will ensure the fix will appear in the release note.

**Comment by milaGGL** [comment]
> When merging this pull request ensure you have "fix:" in the prefix in the commit message. This will ensure the fix will appear in the release note.

The feature is supposed to be released in this cycle. can we remove it completely from release note, instead of having 2 note: added this feature, fix it by removing it?

**Comment by ldetmer** [comment]
> > When merging this pull request ensure you have "fix:" in the prefix in the commit message. This will ensure the fix will appear in the release note.
> 
> The feature is supposed to be released in this cycle. can we remove it completely from release note, instead of having 2 note: added this feature, fix it by removing it?

I can manually update release notes to remove this

**Review by cherylEnkidu — APPROVED** [review]

**Comment by suztomo** [comment]
> I can manually update release notes to remove this

Yes, that works.

**Comment by suztomo** [comment]
clirr check failed https://github.com/googleapis/java-firestore/actions/runs/10927804193/job/30335326929?pr=1833

> 8001: com.google.cloud.firestore.encoding.CustomClassMapper: Class com.google.cloud.firestore.encoding.CustomClassMapper removed


I marked the check as non-required temporarily.

**Pull request merged**
