### PR TITLE
feat: use SecureRandom instead of Random to reduce the chance of auto-id collisions

### LINKED ISSUE #155: Use SecureRandom instead of Random to reduce the chance of auto-id collisions
To reduce the likelihood of automatically-generated document ID collisions, the usage of `java.util.Random` should be upgraded to the more cryptographically-secure random number generator `java.security.SecureRandom`.

FYI, this change has already been made to the Android SDK: https://github.com/firebase/firebase-android-sdk/pull/1250

### PR DESCRIPTION
**Pull request by dconeybe**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #155 ☕️

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Do we know if users have ran into any issues with this sort of switch due to SecureRandom blocking to return values until there is enough entropy? 

> Note: Depending on the implementation, the generateSeed and nextBytes methods may block as entropy is being gathered, for example, if they need to read from /dev/random on various Unix-like operating systems. [1]

[1] https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

**Comment by dconeybe** [comment]
@BenWhitehead I do not know if this would be an issue.  I'll look into it though.  I could see it potentially being an issue with the Android SDK (where the change to SecureRandom has already occurred), where blocking the main thread is strongly discouraged; however, for a server-side SDK I wouldn't anticipate it being an issue.

**Comment by BenWhitehead** [comment]
The main location I'd worry about it in the server side SDK would be in some of our "lean" environments, i.e. Cloud Functions, App Engine etc

**Comment by BenWhitehead** [comment]
I've sent a question to several folks on my team to see if they've ran into anything around entropy in those environments and will report back if I hear anything.

**Comment by dconeybe** [comment]
@BenWhitehead: @wilhuff pointed out that SecureRandom will not block in the way that it is used in this PR: https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/.  At least, it won't block on Mac or Linux.  In Windows, it's unclear if it will block or not.  But do those "lean environments" you referred to include Windows machines?

**Comment by BenWhitehead** [comment]
I believe all the lean environments are linux/container based so `/dev/urandom` is probably a safe assumption, I'll go ahead an approve and merge this.

**Pull request merged**
